### ISSUE TITLE
ServiceOfferings

### ISSUE THREAD

**Issue by mschaepers** [schubergphilis/psCloudstack#1]
Hi,

first of all, thanks for this great module. It saves tons of work.
I'm able to create domains, accounts, vpc, networks, ACLs, private gateways and so on.

I have now a cosmetic issue regarding createServiceOfferings or updateServiceOfferings, see here is a example:

> updateServiceOffering -id 61edf361-86b8-4b9e-9536-b89d2da1983c -name "Windows Server - Standard DemoVPC1"

completionStatus          : True
cpunumber                 : 2
cpuspeed                  : 2000
created                   : 2016-09-11T17:49:55+0200
defaultuse                : false
deploymentplanner         : 
diskBytesReadRate         : 
diskBytesWriteRate        : 
diskIopsReadRate          : 
diskIopsWriteRate         : 
displaytext               : 2+vCPU,+2+GHz,+8+GB+RAM
domain                    : DemoVPC1
domainid                  : 2ccc92d0-758a-4173-ab51-f73368560d71
hosttags                  : 
hypervisorsnapshotreserve : 
id                        : 61edf361-86b8-4b9e-9536-b89d2da1983c
iscustomized              : false
iscustomizediops          : 
issystem                  : false
isvolatile                : false
limitcpuuse               : false
maxiops                   : 
memory                    : 8192
miniops                   : 
name                      : Windows+Server+-+Standard+DemoVPC1
networkrate               : 
offerha                   : false
provisioningtype          : thin
serviceofferingdetails    : 
storagetype               : shared
systemvmtype              : 
tags                      : 

as you can see, the response shows that white spaces has been replaced with a plus. Same happens for displaytext. I've already tried to replace the spaces with %20, no luck on that.

Any idea?

Mauricio

**Comment by hvveen** [comment]
Hi Maurico,

Thanks for using and appreciating psCloudstack. I think I know what is causing this behavior and I will look into it as I am currently working on a new release of psCloudstack.

Best regards, Hans

**Comment by hvveen** [comment]
Hi Maurico,

I found (and solved) the issue. Please let me know whether psCloudstack is behaving the way to want and expect it too.

KR, Hans
